import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

interface Transaction {
  id: string;
  amount: number;
  token_type: string;
  from_address: string;
  to_address: string;
  tx_hash: string;
  status: string;
  created_at: string;
}

export const exportToCSV = (transactions: Transaction[], filename: string = "transactions") => {
  const headers = ["Date", "Type", "Amount", "Token", "From", "To", "Tx Hash", "Status"];
  
  const rows = transactions.map((tx) => [
    new Date(tx.created_at).toLocaleString(),
    tx.from_address ? "Received" : "Sent",
    tx.amount.toString(),
    tx.token_type,
    tx.from_address?.slice(0, 10) + "..." || "-",
    tx.to_address?.slice(0, 10) + "..." || "-",
    tx.tx_hash || "-",
    tx.status,
  ]);

  const csvContent = [
    headers.join(","),
    ...rows.map((row) => row.map((cell) => `"${cell}"`).join(",")),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}_${new Date().toISOString().split("T")[0]}.csv`;
  link.click();
};

export const exportToPDF = (
  transactions: Transaction[],
  filename: string = "transactions",
  title: string = "Transaction History"
) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setTextColor(0, 231, 255); // Cyan color
  doc.text(title, 14, 22);

  // Subtitle with date
  doc.setFontSize(10);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  doc.text(`Total transactions: ${transactions.length}`, 14, 36);

  // Calculate totals by token
  const totals: Record<string, number> = {};
  transactions.forEach((tx) => {
    if (!totals[tx.token_type]) totals[tx.token_type] = 0;
    totals[tx.token_type] += tx.amount;
  });

  // Summary
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text("Summary by Token:", 14, 46);
  
  let yPos = 52;
  Object.entries(totals).forEach(([token, amount]) => {
    doc.setFontSize(10);
    doc.text(`${token}: ${amount.toLocaleString()}`, 20, yPos);
    yPos += 6;
  });

  // Table
  const tableData = transactions.map((tx) => [
    new Date(tx.created_at).toLocaleDateString(),
    tx.amount.toLocaleString(),
    tx.token_type,
    tx.from_address ? tx.from_address.slice(0, 8) + "..." : "-",
    tx.status,
  ]);

  autoTable(doc, {
    head: [["Date", "Amount", "Token", "From", "Status"]],
    body: tableData,
    startY: yPos + 10,
    theme: "striped",
    headStyles: {
      fillColor: [0, 231, 255],
      textColor: [0, 0, 0],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    styles: {
      fontSize: 8,
      cellPadding: 3,
    },
  });

  doc.save(`${filename}_${new Date().toISOString().split("T")[0]}.pdf`);
};

export const exportRewardsToPDF = (
  rewards: any[],
  totalEarned: number,
  username: string = "User"
) => {
  const doc = new jsPDF();

  // Header with gradient effect simulation
  doc.setFillColor(0, 231, 255);
  doc.rect(0, 0, 210, 40, "F");
  
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text("FUN PLAY CAMLY Rewards", 14, 25);

  doc.setFontSize(12);
  doc.text(`Report for: ${username}`, 14, 35);

  // Total earned section
  doc.setFillColor(255, 215, 0); // Gold
  doc.roundedRect(14, 50, 182, 30, 3, 3, "F");
  
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Total CAMLY Earned", 20, 62);
  
  doc.setFontSize(24);
  doc.setTextColor(0, 0, 0);
  doc.text(`${totalEarned.toLocaleString()} CAMLY`, 20, 75);

  // Rewards breakdown
  const tableData = rewards.map((r) => [
    new Date(r.created_at).toLocaleDateString(),
    r.reward_type,
    `+${Number(r.amount).toLocaleString()}`,
    r.videos?.title?.slice(0, 30) || "-",
  ]);

  autoTable(doc, {
    head: [["Date", "Type", "Amount", "Content"]],
    body: tableData,
    startY: 90,
    theme: "striped",
    headStyles: {
      fillColor: [122, 43, 255], // Purple
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
    },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by FUN PLAY Web3`,
      105,
      doc.internal.pageSize.height - 10,
      { align: "center" }
    );
  }

  doc.save(`CAMLY_Rewards_${new Date().toISOString().split("T")[0]}.pdf`);
};
